/**
 * In-memory LRU certificate cache.
 *
 * Caches per-domain TLS certificates generated by the MITM proxy.
 * Each entry has a TTL (default 30 days) and the cache has a max size
 * (default 200 entries). Expired entries are evicted lazily on access.
 *
 * Used by the MITM handler's SNI callback to avoid regenerating certs
 * for every new TLS connection to the same domain.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface CertCacheEntry<T> {
  value: T;
  expiresAt: number;
}

export interface CertCacheOptions {
  /** Maximum number of entries (default: 200). */
  maxEntries?: number;
  /** TTL in milliseconds (default: 30 days). */
  ttlMs?: number;
}

// ─── Constants ──────────────────────────────────────────────────────────────

const DEFAULT_MAX_ENTRIES = 200;
const DEFAULT_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

// ─── Cache ──────────────────────────────────────────────────────────────────

/**
 * LRU cache with TTL expiration for per-domain TLS certificates.
 *
 * Uses a Map for O(1) access with insertion-order iteration for LRU eviction.
 * Expired entries are cleaned up lazily on get/getOrCreate.
 */
export class CertCache<T> {
  private readonly cache = new Map<string, CertCacheEntry<T>>();
  private readonly maxEntries: number;
  private readonly ttlMs: number;

  constructor(options?: CertCacheOptions) {
    this.maxEntries = options?.maxEntries ?? DEFAULT_MAX_ENTRIES;
    this.ttlMs = options?.ttlMs ?? DEFAULT_TTL_MS;
  }

  /**
   * Get a cached value. Returns undefined if not found or expired.
   * Refreshes LRU position on hit.
   */
  get(key: string): T | undefined {
    const entry = this.cache.get(key);
    if (!entry) return undefined;

    if (Date.now() > entry.expiresAt) {
      this.cache.delete(key);
      return undefined;
    }

    // Refresh LRU position: delete and re-insert
    this.cache.delete(key);
    this.cache.set(key, entry);
    return entry.value;
  }

  /**
   * Set a value in the cache. Evicts LRU entry if at capacity.
   */
  set(key: string, value: T): void {
    // Remove existing entry to refresh position
    this.cache.delete(key);

    // Evict LRU (first entry in Map iteration order) if at capacity
    if (this.cache.size >= this.maxEntries) {
      const firstKey = this.cache.keys().next().value as string;
      this.cache.delete(firstKey);
    }

    this.cache.set(key, {
      value,
      expiresAt: Date.now() + this.ttlMs,
    });
  }

  /**
   * Get or create a cached value. If the key is not in cache (or expired),
   * calls the generator function and caches the result.
   *
   * The generator is called synchronously — for async cert generation,
   * wrap in a promise externally.
   */
  async getOrCreate(key: string, generator: (key: string) => T | Promise<T>): Promise<T> {
    const cached = this.get(key);
    if (cached !== undefined) return cached;

    const value = await generator(key);
    this.set(key, value);
    return value;
  }

  /** Number of entries currently in cache (including potentially expired). */
  get size(): number {
    return this.cache.size;
  }

  /** Remove all entries. */
  clear(): void {
    this.cache.clear();
  }

  /** Check if a key exists and is not expired. */
  has(key: string): boolean {
    const entry = this.cache.get(key);
    if (!entry) return false;
    if (Date.now() > entry.expiresAt) {
      this.cache.delete(key);
      return false;
    }
    return true;
  }
}
