/**
 * macOS launchd plist generator.
 *
 * Generates launchd user agent plist files for FlowHelm on macOS.
 * Each user gets an `ai.flowhelm.plist` installed to their
 * `~/Library/LaunchAgents/` directory.
 *
 * The agent runs `flowhelm start` as the user, with KeepAlive=true
 * for always-on operation and RunAtLoad=true to start on login.
 *
 * Management commands:
 *   Load:    launchctl load ~/Library/LaunchAgents/ai.flowhelm.plist
 *   Unload:  launchctl unload ~/Library/LaunchAgents/ai.flowhelm.plist
 *   Restart: launchctl kickstart -k gui/$(id -u)/ai.flowhelm
 *   Status:  launchctl list | grep flowhelm
 */

import { writeFile, mkdir, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

// ─── Types ──────────────────────────────────────────────────────────────────

export interface LaunchdGeneratorOptions {
  /** macOS username. */
  username: string;
  /** Path to the flowhelm binary. Default: /usr/local/bin/flowhelm */
  binaryPath?: string;
  /** Path to node binary. Default: /usr/local/bin/node */
  nodePath?: string;
  /** User's home directory. */
  homeDir: string;
  /** Agent runtime mode. */
  agentRuntime?: 'cli' | 'sdk';
}

export interface LaunchdPlist {
  /** Full path where the plist file will be written. */
  plistPath: string;
  /** Plist file content. */
  content: string;
  /** Service label (e.g., ai.flowhelm). */
  label: string;
}

// ─── Constants ──────────────────────────────────────────────────────────────

const LAUNCHD_LABEL = 'ai.flowhelm';
const PLIST_FILENAME = `${LAUNCHD_LABEL}.plist`;

// ─── Generator ──────────────────────────────────────────────────────────────

/**
 * Generate the launchd plist file content.
 */
export function generateLaunchdPlist(options: LaunchdGeneratorOptions): LaunchdPlist {
  const binaryPath = options.binaryPath ?? '/usr/local/bin/flowhelm';
  const configDir = join(options.homeDir, '.flowhelm');
  const logDir = join(configDir, 'logs');

  // Build environment variables
  const envEntries: Array<[string, string]> = [
    ['HOME', options.homeDir],
    ['FLOWHELM_CONFIG_DIR', configDir],
    ['NODE_ENV', 'production'],
    ['PATH', '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin'],
  ];

  if (options.agentRuntime) {
    envEntries.push(['FLOWHELM_AGENT_RUNTIME', options.agentRuntime]);
  }

  const envXml = envEntries
    .map(
      ([key, value]) =>
        `        <key>${escapeXml(key)}</key>\n        <string>${escapeXml(value)}</string>`,
    )
    .join('\n');

  const content = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!--
  FlowHelm AI Agent Orchestrator — launchd user agent for ${options.username}
  Generated by flowhelm setup. Do not edit manually.

  Load:    launchctl load ~/Library/LaunchAgents/${PLIST_FILENAME}
  Unload:  launchctl unload ~/Library/LaunchAgents/${PLIST_FILENAME}
  Restart: launchctl kickstart -k gui/$(id -u)/${LAUNCHD_LABEL}
  Logs:    tail -f ${logDir}/flowhelm.log
-->
<dict>
    <key>Label</key>
    <string>${LAUNCHD_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${escapeXml(binaryPath)}</string>
        <string>start</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${escapeXml(options.homeDir)}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>EnvironmentVariables</key>
    <dict>
${envXml}
    </dict>
    <key>StandardOutPath</key>
    <string>${escapeXml(logDir)}/flowhelm.log</string>
    <key>StandardErrorPath</key>
    <string>${escapeXml(logDir)}/flowhelm.error.log</string>
    <key>ThrottleInterval</key>
    <integer>5</integer>
    <key>ProcessType</key>
    <string>Interactive</string>
</dict>
</plist>
`;

  const plistDir = join(options.homeDir, 'Library', 'LaunchAgents');
  const plistPath = join(plistDir, PLIST_FILENAME);

  return { plistPath, content, label: LAUNCHD_LABEL };
}

/**
 * Write the launchd plist file to disk.
 * Creates parent directories (~/Library/LaunchAgents/) and log directory as needed.
 */
export async function installLaunchdService(
  options: LaunchdGeneratorOptions,
): Promise<LaunchdPlist> {
  const plist = generateLaunchdPlist(options);
  const plistDir = join(options.homeDir, 'Library', 'LaunchAgents');
  const logDir = join(options.homeDir, '.flowhelm', 'logs');

  await mkdir(plistDir, { recursive: true });
  await mkdir(logDir, { recursive: true });
  await writeFile(plist.plistPath, plist.content, { mode: 0o644 });

  return plist;
}

/**
 * Remove the launchd plist file.
 */
export async function removeLaunchdService(homeDir: string): Promise<void> {
  const plistPath = join(homeDir, 'Library', 'LaunchAgents', PLIST_FILENAME);
  try {
    await rm(plistPath);
  } catch (err) {
    if (err instanceof Error && 'code' in err && (err as NodeJS.ErrnoException).code === 'ENOENT') {
      return; // Already removed
    }
    throw err;
  }
}

/**
 * Read an existing launchd plist file.
 * Returns null if the file doesn't exist.
 */
export async function readLaunchdService(homeDir: string): Promise<string | null> {
  const plistPath = join(homeDir, 'Library', 'LaunchAgents', PLIST_FILENAME);
  try {
    return await readFile(plistPath, 'utf-8');
  } catch {
    return null;
  }
}

/** Escape special XML characters in plist values. */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
