/**
 * Systemd user service generator.
 *
 * Generates systemd user unit files for per-user FlowHelm orchestrator
 * instances. Each user gets a `flowhelm.service` installed to their
 * `~/.config/systemd/user/` directory.
 *
 * The service runs `flowhelm start` as the user, with Restart=always
 * for always-on operation.
 */

import { writeFile, mkdir, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ServiceGeneratorOptions {
  /** Linux username (e.g., flowhelm-stan). */
  username: string;
  /** Path to the flowhelm binary. Default: /usr/local/bin/flowhelm */
  binaryPath?: string;
  /** User's home directory. */
  homeDir: string;
  /** Per-user RAM limit (e.g., 4G). */
  ramLimit?: string;
  /** Per-user CPU limit (number of cores). */
  cpuLimit?: number;
  /** Agent runtime mode. */
  agentRuntime?: 'cli' | 'sdk';
}

export interface ServiceUnit {
  /** Full path where the unit file will be written. */
  unitPath: string;
  /** Unit file content. */
  content: string;
  /** Service name (e.g., flowhelm.service). */
  serviceName: string;
}

// ─── Generator ──────────────────────────────────────────────────────────────

/**
 * Generate the systemd user unit file content.
 */
export function generateServiceUnit(options: ServiceGeneratorOptions): ServiceUnit {
  const binaryPath = options.binaryPath ?? '/usr/bin/flowhelm';
  const configDir = join(options.homeDir, '.flowhelm');
  const serviceName = 'flowhelm.service';

  // Build environment variables
  const envLines: string[] = [
    `Environment=HOME=${options.homeDir}`,
    `Environment=FLOWHELM_CONFIG_DIR=${configDir}`,
    `Environment=NODE_ENV=production`,
  ];

  if (options.agentRuntime) {
    envLines.push(`Environment=FLOWHELM_AGENT_RUNTIME=${options.agentRuntime}`);
  }

  const content = `# FlowHelm orchestrator service for ${options.username}
# Generated by flowhelm admin add-user. Do not edit manually.
#
# Enable:  systemctl --user enable flowhelm.service
# Start:   systemctl --user start flowhelm.service
# Status:  systemctl --user status flowhelm.service
# Logs:    journalctl --user -u flowhelm.service -f

[Unit]
Description=FlowHelm AI Agent Orchestrator
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${binaryPath} start
WorkingDirectory=${options.homeDir}
Restart=always
RestartSec=5
${envLines.join('\n')}

# Graceful shutdown: send SIGTERM, wait 30s, then SIGKILL
TimeoutStopSec=30
KillMode=mixed
KillSignal=SIGTERM

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=flowhelm

[Install]
WantedBy=default.target
`;

  const unitDir = join(options.homeDir, '.config', 'systemd', 'user');
  const unitPath = join(unitDir, serviceName);

  return { unitPath, content, serviceName };
}

/**
 * Write the systemd user service unit file to disk.
 * Creates parent directories as needed.
 */
export async function installService(options: ServiceGeneratorOptions): Promise<ServiceUnit> {
  const unit = generateServiceUnit(options);
  await mkdir(join(options.homeDir, '.config', 'systemd', 'user'), { recursive: true });
  await writeFile(unit.unitPath, unit.content, { mode: 0o644 });
  return unit;
}

/**
 * Remove the systemd user service unit file.
 */
export async function removeService(homeDir: string): Promise<void> {
  const unitPath = join(homeDir, '.config', 'systemd', 'user', 'flowhelm.service');
  try {
    await rm(unitPath);
  } catch (err) {
    if (err instanceof Error && 'code' in err && (err as NodeJS.ErrnoException).code === 'ENOENT') {
      return; // Already removed
    }
    throw err;
  }
}

/**
 * Read an existing service unit file.
 * Returns null if the file doesn't exist.
 */
export async function readService(homeDir: string): Promise<string | null> {
  const unitPath = join(homeDir, '.config', 'systemd', 'user', 'flowhelm.service');
  try {
    return await readFile(unitPath, 'utf-8');
  } catch {
    return null;
  }
}
